"""
AIS Vessel Stay Detection & Anomaly Detection
Data schema: entity_id, lat, lon, timestamp, vessel_type, sog_knots, is_anomalous, anomaly_type

Usage:S
    df = pd.read_csv('ais_small.csv')
    results = run_pipeline(df)
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, f1_score

import pandas as pd
import folium
from folium.plugins import MarkerCluster


# CONSTANTS
STAY_RADIUS_KM        = 1    # CHANGED
STAY_MIN_DURATION_M   = 60     # CHANGED 
SPEED_STAY_THRESH     = 2    # CHANGED
AIS_GAP_THRESHOLD_MIN = 60      # minutes of silence before flagging "dark ship"
SPOOF_DIST_KM         = 50      # absolute jump (km) considered implausible
SPOOF_IMPLIED_KNOTS   = 60      # implied speed (knots) considered implausible
MIN_GROUP_SIZE_FOR_TYPE_MODEL = 50  # below this, fall back to the global model


# If you want to treat anything under 2 knots as stationary instead of 1 kn:
# SPEED_STAY_THRESH   = 2.0    # knots threshold for low_speed_flag



# HELPERS
def haversine_km(lat1, lon1, lat2, lon2):
    """Vectorized haversine distance in km."""
    R = 6371.0
    phi1, phi2 = np.radians(lat1), np.radians(lat2)
    dphi = np.radians(lat2 - lat1)
    dlam = np.radians(lon2 - lon1)
    a = np.sin(dphi / 2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(dlam / 2)**2
    return 2 * R * np.arcsin(np.sqrt(a))



# filename: detect_stays_dbscan.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import numpy as np
import pandas as pd
from sklearn.cluster import DBSCAN

# Earth’s radius in km
EARTH_RADIUS_KM = 6371.0

def detect_stays_dbscan(group: pd.DataFrame) -> pd.DataFrame:
    df = group.sort_values("timestamp").copy().reset_index(drop=True)
    coords = np.radians(df[["lat", "lon"]].values)
    # DBSCAN eps in radians
    eps_rad = STAY_RADIUS_KM / EARTH_RADIUS_KM
    # Minimum 2 samples to form a cluster
    db = DBSCAN(eps=eps_rad, min_samples=2, metric="haversine").fit(coords)
    df["stay_id"] = db.labels_  # -1 = noise
    
    # Initialize flags
    df["is_stay"] = False
    df["stay_center_lat"] = np.nan
    df["stay_center_lon"] = np.nan
    df["stay_duration_min"] = np.nan

    # For each spatial cluster
    stay_counter = 0
    for cluster_label, grp in df[df["stay_id"] >= 0].groupby("stay_id"):
        times = pd.to_datetime(grp["timestamp"]).sort_values()
        # Identify contiguous sequences where time gaps ≤ STAY_MIN_DURATION_M
        time_diffs = times.diff().dt.total_seconds().div(60).fillna(0)
        segment_ids = (time_diffs > STAY_MIN_DURATION_M).cumsum()
        for seg, idxs in grp.groupby(segment_ids).groups.items():
            seg_times = times.loc[idxs]
            duration = (seg_times.max() - seg_times.min()).total_seconds() / 60
            if duration >= STAY_MIN_DURATION_M:
                # mark this segment as a stay
                df.loc[idxs, "is_stay"] = True
                df.loc[idxs, ["stay_center_lat","stay_center_lon"]] = (
                    grp.loc[idxs, ["lat","lon"]].mean().values
                )
                df.loc[idxs, "stay_duration_min"] = duration
                df.loc[idxs, "stay_id"] = stay_counter
                stay_counter += 1

    return df

def run_stay_detection(df: pd.DataFrame) -> pd.DataFrame:
    results = []
    for eid, group in df.groupby("entity_id"):
        g = detect_stays_dbscan(group)
        g["entity_id"] = eid
        results.append(g)
    return pd.concat(results, ignore_index=True)



# FEATURE ENGINEERING
def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Per-ping features for anomaly detection.

    Speed-based:
        sog_knots, speed_delta, speed_z (z-score within vessel)

    Spatial / movement:
        dist_from_prev_km, bearing_delta (heading change)
        dist_from_median_pos (how far from vessel's typical area)

    Temporal / reporting:
        time_gap_min (minutes since this vessel's previous ping --
            the key signal for AIS "dark" periods)
        hour_of_day, day_of_week

    Stay-based (uses stay detection output):
        is_stay, stay_duration_min (0 if not a stay)
    """
    df = df.copy()
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values(["entity_id", "timestamp"])

    # ── reporting-gap feature (do this first, while sorted)
    df["time_gap_min"] = (
        df.groupby("entity_id")["timestamp"]
          .diff()
          .dt.total_seconds()
          .div(60)
          .fillna(0)
    )

    # ── speed features
    df["speed_delta"] = df.groupby("entity_id")["sog_knots"].diff().fillna(0)

    def z_score(s):
        std = s.std()
        return (s - s.mean()) / std if std > 0 else s * 0
    df["speed_z"] = df.groupby("entity_id")["sog_knots"].transform(z_score)

    # ── spatial features
    df["prev_lat"] = df.groupby("entity_id")["lat"].shift(1)
    df["prev_lon"] = df.groupby("entity_id")["lon"].shift(1)
    valid = df["prev_lat"].notna()
    df.loc[valid, "dist_from_prev_km"] = haversine_km(
        df.loc[valid, "lat"], df.loc[valid, "lon"],
        df.loc[valid, "prev_lat"], df.loc[valid, "prev_lon"]
    )
    df["dist_from_prev_km"] = df["dist_from_prev_km"].fillna(0)

    # Bearing (heading) delta
    def bearing(lat1, lon1, lat2, lon2):
        dlon = np.radians(lon2 - lon1)
        lat1r, lat2r = np.radians(lat1), np.radians(lat2)
        x = np.sin(dlon) * np.cos(lat2r)
        y = np.cos(lat1r) * np.sin(lat2r) - np.sin(lat1r) * np.cos(lat2r) * np.cos(dlon)
        return (np.degrees(np.arctan2(x, y)) + 360) % 360

    df.loc[valid, "bearing"] = bearing(
        df.loc[valid, "prev_lat"], df.loc[valid, "prev_lon"],
        df.loc[valid, "lat"],      df.loc[valid, "lon"]
    )
    df["bearing"] = df["bearing"].fillna(0)
    df["prev_bearing"] = df.groupby("entity_id")["bearing"].shift(1).fillna(0)
    df["bearing_delta"] = ((df["bearing"] - df["prev_bearing"] + 180) % 360) - 180

    # Distance from vessel's median position (OOD location signal)
    med = df.groupby("entity_id")[["lat", "lon"]].median().rename(
        columns={"lat": "med_lat", "lon": "med_lon"}
    )
    df = df.join(med, on="entity_id")
    df["dist_from_median_km"] = haversine_km(
        df["lat"], df["lon"], df["med_lat"], df["med_lon"]
    )

    # ── stay features (from stay detection)
    df["stay_duration_min"] = df["stay_duration_min"].fillna(0)
    df["is_stay_int"] = df["is_stay"].astype(int)

    # ── temporal features
    df["hour_of_day"]  = df["timestamp"].dt.hour
    df["day_of_week"]  = df["timestamp"].dt.dayofweek

    df.drop(columns=["prev_lat", "prev_lon", "prev_bearing",
                     "med_lat", "med_lon"], inplace=True)
    return df


# 3. ANOMALY DETECTION
# NOTE: raw sog_knots is intentionally excluded. "Normal" speed varies hugely
# by vessel type (a 25kt passenger ferry vs a 5kt fishing boat), so the
# per-vessel z-scored speed (speed_z) is the meaningful signal. Combined with
# per-vessel-type models below, this keeps fast-but-normal vessels from
# dominating the flagged set.
FEATURE_COLS = [
    "speed_z",
    "speed_delta",
    "dist_from_prev_km",
    "bearing_delta",
    "dist_from_median_km",
    "stay_duration_min",
    "is_stay_int",
    "time_gap_min",
    "hour_of_day",
]


def train_isolation_forest_by_type(df: pd.DataFrame, contamination: float = 0.02):
    """
    Train one Isolation Forest per vessel_type, plus a global fallback model
    for any type with too few rows to train reliably.

    contamination is a *prior assumption* about anomaly rate -- it is NOT
    tuned against ground-truth labels (that would be leakage). 0.02 is a
    starting point; if you want to refine it without peeking at labels,
    look at the distribution of anomaly_score per vessel_type (e.g.
    df.groupby('vessel_type')['anomaly_score'].describe() or a histogram)
    and look for a natural break/elbow rather than matching a known rate.

    Returns: dict of models keyed by vessel_type (+ "__global__"),
             matching dict of scalers.
    """
    models, scalers = {}, {}

    X_all = df[FEATURE_COLS].fillna(0).values
    global_scaler = StandardScaler().fit(X_all)
    global_model = IsolationForest(
        n_estimators=200, contamination=contamination, random_state=42, n_jobs=-1
    ).fit(global_scaler.transform(X_all))
    models["__global__"] = global_model
    scalers["__global__"] = global_scaler

    for vtype, group in df.groupby("vessel_type"):
        if len(group) < MIN_GROUP_SIZE_FOR_TYPE_MODEL:
            continue  # too few samples -- predict_anomalies_by_type falls back to global

        X = group[FEATURE_COLS].fillna(0).values
        scaler = StandardScaler().fit(X)
        model = IsolationForest(
            n_estimators=200, contamination=contamination, random_state=42, n_jobs=-1
        ).fit(scaler.transform(X))

        models[vtype] = model
        scalers[vtype] = scaler

    return models, scalers


def predict_anomalies_by_type(df: pd.DataFrame, models, scalers) -> pd.DataFrame:
    """
    Predict anomalies using the per-vessel-type models (falling back to the
    global model for unseen / small vessel types).

    Returns df with added:
        anomaly_score  (raw IF score, lower = more anomalous)
        pred_anomalous (bool)
    """
    df = df.copy()
    df["anomaly_score"]  = np.nan
    df["pred_anomalous"] = False

    for vtype, group in df.groupby("vessel_type"):
        key = vtype if vtype in models else "__global__"
        X = group[FEATURE_COLS].fillna(0).values
        X_scaled = scalers[key].transform(X)

        df.loc[group.index, "anomaly_score"]  = models[key].score_samples(X_scaled)
        df.loc[group.index, "pred_anomalous"] = models[key].predict(X_scaled) == -1

    return df


# RULE-BASED LAYER (transparent, on top of IF)
def rule_based_flags(df: pd.DataFrame) -> pd.DataFrame:
    """
    Lightweight rules that map to known anomaly types in your data:

      dark_ship    -> AIS goes silent for an extended period (time_gap_min)
      spoofing     -> a position jump that's physically implausible given
                       the elapsed time (or just very large outright)
      aggression   -> sudden, large, simultaneous change in speed and heading
      illegal_fish -> low-speed loitering far from a fishing vessel's
                       usual grounds
    """
    df = df.copy()

    # dark_ship: gap in AIS reporting longer than expected
    df["rule_dark_ship"] = df["time_gap_min"] > AIS_GAP_THRESHOLD_MIN

    # spoofing: implausible jump given time elapsed, OR a huge jump regardless
    df["implied_speed_knots"] = np.where(
        df["time_gap_min"] > 0,
        (df["dist_from_prev_km"] / 1.852) / (df["time_gap_min"] / 60.0),
        0.0,
    )
    df["rule_spoofing"] = (
        (df["dist_from_prev_km"] > SPOOF_DIST_KM) |
        (df["implied_speed_knots"] > SPOOF_IMPLIED_KNOTS)
    )

    df["rule_impossible_speed"] = df["sog_knots"] > 40.0 


    # aggression: abrupt, large change in both speed and heading at once
    df["rule_aggression"] = (
        (df["speed_delta"].abs() > 15) & (df["bearing_delta"].abs() > 120)
    )

    # illegal_fish: fishing vessel loitering well outside its normal area
    df["rule_illegal_fish"] = (
        (df["sog_knots"] < 2) &
        (df["dist_from_median_km"] > 20)
    )

    df["rule_transshipment"] = (
    df.groupby("entity_id")["sog_knots"]
      .rolling(window=4, min_periods=4)
      .max()
      .reset_index(level=0, drop=True) < 1.0
)

    # df["any_rule_flag"] = (
    #     df["rule_dark_ship"] | df["rule_spoofing"] |
    #     df["rule_aggression"] | df["rule_illegal_fish"]
    #)

    df["any_rule_flag"] = (
        df["rule_impossible_speed"] | 
        df["rule_aggression"] | 
        df["rule_transshipment"] | 
        df["rule_illegal_fish"]
    )
    
    return df


# EVALUATION (uses ground truth cols)
def evaluate(df: pd.DataFrame):
    """
    Compare predictions to ground truth (is_anomalous).
    Prints classification report. Returns F1.
    """
    y_true = df["is_anomalous"].astype(int)
    y_pred = df["pred_anomalous"].astype(int)

    print("=" * 50)
    print("ANOMALY DETECTION — Classification Report")
    print("=" * 50)
    print(classification_report(y_true, y_pred, target_names=["Normal", "Anomalous"]))

    f1 = f1_score(y_true, y_pred)
    print(f"F1 Score: {f1:.4f}")

    # Rule-based comparison
    print("\nRule-Based Layer Flags:")
    for col in ["rule_dark_ship", "rule_spoofing", "rule_aggression", "rule_illegal_fish"]:
        if col in df.columns:
            prec = (df[col] & (y_true == 1)).sum() / df[col].sum() \
                   if df[col].sum() > 0 else 0
            print(f"  {col:25s}: {df[col].sum():5d} flagged | precision={prec:.2f}")

    return f1


# FULL PIPELINE
def run_pipeline(df: pd.DataFrame, contamination: float = 0.02) -> pd.DataFrame:
    """
    End-to-end:
      1. Stay detection
      2. Feature engineering
      3. Per-vessel-type Isolation Forest anomaly detection
      4. Rule-based overlay
      5. Combine model + rules (OR) for final prediction
      6. Evaluation vs ground truth

    Args:
        df: raw AIS dataframe
        contamination: prior assumption about per-type anomaly rate
            (NOT tuned to ground truth -- see train_isolation_forest_by_type)
    """
    print("Step 1: Stay detection...")
    df = run_stay_detection(df)

    print("Step 2: Feature engineering...")
    df = build_features(df)

    print("Step 3: Training per-vessel-type Isolation Forests...")
    models, scalers = train_isolation_forest_by_type(df, contamination=contamination)

    print("Step 4: Predicting anomalies...")
    df = predict_anomalies_by_type(df, models, scalers)

    print("Step 5: Rule-based flags...")
    df = rule_based_flags(df)

    # Final prediction: flagged by the model OR by any transparent rule.
    # This favors recall (catching more true anomalies) at some cost to
    # precision -- adjust by dropping weak rules or raising `contamination`
    # if you need fewer false positives instead.
    df["pred_anomalous"] = df["pred_anomalous"] | df["any_rule_flag"]

    print("Step 6: Evaluation...\n")
    evaluate(df)

    return df


def visualize_staypoints(df: pd.DataFrame,
                         map_center=(21.5, -80.0),
                         zoom_start=6,
                         marker_radius=5,
                         output_html="staypoints_cuba.html"):
    """
    Given a DataFrame with stay detection applied (with columns
    is_stay, stay_id, stay_center_lat, stay_center_lon, stay_duration_min),
    plot one marker per stay_id on a Folium map centered on Cuba.
    """
    # Filter only stay points and dedupe per stay_id
    stays = (
        df[df["is_stay"]]
        .drop_duplicates(subset="stay_id")
        .loc[:, ["stay_id", "stay_center_lat", "stay_center_lon", "stay_duration_min"]]
    )

    # Initialize map
    m = folium.Map(location=map_center, zoom_start=zoom_start, tiles="CartoDB positron")

    # Use MarkerCluster for readability
    cluster = MarkerCluster().add_to(m)

    for _, row in stays.iterrows():
        lat, lon = row["stay_center_lat"], row["stay_center_lon"]
        dur = row["stay_duration_min"]
        popup = (f"Stay ID: {row['stay_id']}<br>"
                 f"Duration: {dur:.1f} min")
        folium.CircleMarker(
            location=(lat, lon),
            radius=marker_radius,
            color="blue",
            fill=True,
            fill_opacity=0.6,
            popup=popup
        ).add_to(cluster)

    # Save to HTML
    m.save(output_html)
    print(f"Map with {len(stays)} staypoints saved to {output_html}")


# if __name__ == "__main__":

#     df = pd.read_csv("ais_small.csv")
#     # 1) run your existing stay detection
#     df = run_stay_detection(df)
#     # 2) call the visualization helper
#     visualize_staypoints(df, map_center=(21.5, -80.0), zoom_start=6, output_html="staypoints_cuba.html")


# QUICKSTART
if __name__ == "__main__":
    df = pd.read_csv("ais_small.csv")
    results = run_pipeline(df, contamination=0.02)

    # Show sample anomalies
    print("\nSample predicted anomalies:")
    print(
        results[results["pred_anomalous"]]
        [["entity_id", "timestamp", "vessel_type", "sog_knots",
          "anomaly_score", "is_anomalous", "anomaly_type"]]
        .head(10)
        .to_string(index=False)
    )

